#2510010102 - M. Rizky Rinaldy
print("+==================================+")
print("|      Input Anggota Himpunan      |")
print("|      (pisahkan dengan koma)      |")
print("+==================================+")
data_a = input("| Himpunan A : ") 
data_b = input("| Himpunan B : ") 
  
A = set(int(x.strip()) for x in data_a.split(",")) 
B = set(int(x.strip()) for x in data_b.split(",")) 

print("+==================================+")
print("|          Hasil Himpunan          |")
print("+==================================+")
print(f"| A           = {A}") 
print(f"| B           = {B}") 
print(f"| A U B       = {A | B}") 
print(f"| A ∩ B       = {A & B}") 
print(f"| A - B       = {A - B}") 
print(f"| B - A       = {B - A}") 
print(f"| Simetris    = {A ^ B}") 
print("+----------------------------------+")
print()
print("+==================================+")
print("| Dosen: Bpk. Yusri Ikhwani, M.Kom |")
print("|   2510010102 - M. Rizky Rinaldy  |")
print("+==================================+")

input()